import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React, { Suspense, useEffect, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

const LazyGraph = React.lazy(() => import("../components/Graph"));

const Home: NextPage = () => {
  const [isLoaded, setIsLoaded] = useState(false);

  useEffect(() => {
    // Client-side-only code

    setIsLoaded(true);
  });

  return (
    <div className="flex flex-col basis-full h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-row h-{400px} border-b border-gray-600">
        {isLoaded && (
          <Suspense fallback={<div>Loading...</div>}>
            <LazyGraph />
          </Suspense>
        )}
      </div>
      <div className="flex flex-col flex-grow">
        <div className="flex flex-row basis-full">
          <div className="flex flex-col basis-1/2 border-r border-gray-600 justify-start p-2">
            <input type="text" className="border border-gray-400" />
            <input type="text" className="border border-gray-400" />
            <input type="text" className="border border-gray-400" />
            <button className="p-2 border border-gray-600 ">
              Create Entity
            </button>
          </div>
          <div className="flex flex-col basis-1/2">
            <ReactMarkdown children="# hi" remarkPlugins={[remarkGfm]} />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
